spring.config.import=optional:file:.env[.properties]

spring.application.name=ms-usuarios

# Configuracion del servidor
server.port=8081

# Conexion a PostgreSQL
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.access-expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000